version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest  

  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: Identity/Dockerfile
    depends_on:
      - sqldata

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile

